version: "3.8"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: client_c
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - ./client/node_modules
    stdin_open: true
    tty: true
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: server_c
    ports:
      - "4001:4001"
    volumes:
      - ./server:/app
      - ./server/node_modules
